Repository BME-MIT-IET/Brutal-Puppies-iet-2020, pull requests merged in 2020-05, with the labels that each got.

#10 adding codecov workflow
  .github/workflows/main.yml
Labels: technológia fókusz

#13 Adding build github action instead of travis
  .github/workflows/build_workflow.yml
  .travis.yml
  test_requirements.txt
  tox.ini
Labels: technológia fókusz

#18 Fix Sonar Cloud Issues
  algorithms/maths/diffie_hellman_key_exchange.py
  algorithms/maths/euler_totient.py
  algorithms/maths/find_order_simple.py
  algorithms/maths/find_primitive_root_simple.py
  tests/test_maths.py
Labels: technológia fókusz

#7 Volume testing #6
  tests/test_volume_matrix.py
Labels: Termék/felhasználó fókusz

#24 Bdd testing
  features/behave_linear_search.feature
  features/behave_matrix_inversion.feature
  features/behave_pattern_match.feature
  features/steps/behave_linear_search.py
  features/steps/behave_matrix_inversion.py
  features/steps/behave_pattern_match.py
Labels: Termék/felhasználó fókusz

#25 Volume testing arrays
  tests/test_volume_arrays.py
Labels: Termék/felhasználó fókusz

#8 Documentation
  IET-HF.md
  doc/README.md
  doc/Sonarcloud_bug_fix_rb_tree.md
  doc/images/actions.png
  doc/images/bdd_actions_success.png
  doc/images/bdd_linear_fail.png
  doc/images/bdd_linear_success.png
  doc/images/bdd_matrix.png
  doc/images/bdd_pattern_fail.png
  doc/images/bdd_pattern_success.png
  doc/images/bdd_sonar_success.png
  doc/images/bdd_success.png
  doc/images/codecov_comment.png
  doc/images/delete_nth_volume.png
  doc/images/fiuc_success.png
  doc/images/limit_volume.png
  doc/images/move_zeros_volume.png
  doc/images/sample_code_bea.png
  doc/images/sonar_bug_codecov.png
  doc/images/sonar_bug_codecov_success.png
  doc/images/sonar_cloud_bug_fixed.png
  doc/images/sonarcloud_comment.png
  doc/images/strings_codecov.png
  doc/images/test_matrix_success.png
  doc/images/vt_invert.png
  doc/images/vt_multiply.png
  doc/images/vt_sonar_success.png
  doc/images/vt_success.png
  doc/images/vt_tests1.png
  doc/images/vt_tests2.png
  doc/images/vt_tests3.png
  doc/sample_code_bea0113.md
  doc/technologia_fokusz_1.md
  doc/technologia_fokusz_2.md
  doc/technologia_fokusz_CI.md
  doc/termek_es_felhasznaloi_fokusz_1.md
  doc/termek_es_felhasznaloi_fokusz_2.md
  doc/termek_es_felhasznaloi_fokusz_3.md
  doc/tests_for_string_algorithms.md
  doc/tests_to_test_matrix.md
Labels: documentation
